### ISSUE TITLE
Staging environment doesn't work

### ISSUE THREAD

**Issue by bethcollins92** [canonical-web-and-design/charmed-kubeflow.io#15]
The staging link from this [build](https://jenkins.canonical.com/webteam/job/charmed-kubeflow.io-staging/2/console) isn't working. 

[https://staging.charmed-kubeflow.io/](https://staging.charmed-kubeflow.io/)

**Comment by jkfran** [comment]
Waiting on IS to point the domains to our cluster

https://portal.admin.canonical.com/C127619/
