### ISSUE TITLE
Repo not set up to deploy automatically 

### ISSUE THREAD

**Issue by bethcollins92** [canonical-web-and-design/charmed-kubeflow.io#23]

**Comment by anthonydillon** [comment]
Following the "How do I enable..." section in [the demo guide](https://discourse.ubuntu.com/t/demoservice/16862) should get you set up. If you need a hand, shout.

**Comment by albertkol** [comment]
@anthonydillon I added the Webhook. I am not sure how to test it, but I suppose time will confirm if it works or not.
